import 'package:ntk_cms_flutter_base/src/models/entity/base/base_module_entity.dart';
import 'package:ntk_cms_flutter_base/src/models/entity/base/feildinfo/get_properties_info_model.dart';
import 'package:ntk_cms_flutter_base/src/models/entity/enums/enum_build_status_type.dart';
import 'package:ntk_cms_flutter_base/src/models/entity/enums/enum_language.dart';
import 'package:ntk_cms_flutter_base/src/models/entity/enums/enum_record_status.dart';
import 'package:json_annotation/json_annotation.dart';

import 'application_layout_value_model.dart';
import 'application_source_model.dart';
import 'application_theme_config_model.dart';
part 'application_app_model.g.dart';

@JsonSerializable()
class ApplicationAppModel extends BaseModuleEntity<int> {
  @JsonKey(name: 'appKey')
  String? appKey;
  @JsonKey(name: 'lang')
  EnumLanguage? lang;
  @JsonKey(name: 'expireDate')
  DateTime? expireDate;
  @JsonKey(name: 'linkFileIdIcon')
  int? linkFileIdIcon;
  @JsonKey(name: 'linkFileIdLogo')
  int? linkFileIdLogo;
  @JsonKey(name: 'linkFileIdSplashScreen')
  int? linkFileIdSplashScreen;
  @JsonKey(name: 'linkMainImageId')
  int? linkMainImageId;
  @JsonKey(name: 'title')
  String? title;
  @JsonKey(name: 'description')
  String? description;
  @JsonKey(name: 'appVersion')
  int? appVersion;
  @JsonKey(name: 'isPublished')
  bool? isPublished;
  @JsonKey(name: 'linkSourceId')
  int? linkSourceId;
  @JsonKey(name: 'virtual_Source')
  ApplicationSourceModel? virtual_Source;
  @JsonKey(name: 'source')
  ApplicationSourceModel? source;
  @JsonKey(name: 'downloadCount')
  int? downloadCount;
  @JsonKey(name: 'isGlobalUser')
  bool? isGlobalUser;
  @JsonKey(name: 'checkUpdate')
  bool? checkUpdate;
  @JsonKey(name: 'forceUpdate')
  bool? forceUpdate;
  @JsonKey(name: 'allowDirectShareApp')
  bool? allowDirectShareApp;
  @JsonKey(name: 'lastBuildAppKey')
  String? lastBuildAppKey;
  @JsonKey(name: 'lastBuildStatus')
  EnumBuildStatusType? lastBuildStatus;
  @JsonKey(name: 'lastNotificationOrderDate')
  DateTime? lastNotificationOrderDate;
  @JsonKey(name: 'lastBuildOrderDate')
  DateTime? lastBuildOrderDate;
  @JsonKey(name: 'lastBuildRunDate')
  DateTime? lastBuildRunDate;
  @JsonKey(name: 'lastBuildEndDate')
  DateTime? lastBuildEndDate;
  @JsonKey(name: 'lastBuildErrorMessage')
  String? lastBuildErrorMessage;
  @JsonKey(name: 'lastSuccessfullyBuildDate')
  DateTime? lastSuccessfullyBuildDate;
  @JsonKey(name: 'layoutValues')
  List<ApplicationLayoutValueModel>? layoutValues;
  @JsonKey(name: 'buildCount')
  int? buildCount;
  @JsonKey(name: 'linkThemeConfigId')
  int? linkThemeConfigId;
  @JsonKey(name: 'virtual_ThemeConfig')
  ApplicationThemeConfigModel? virtual_ThemeConfig;
  @JsonKey(name: 'themeConfig')
  ApplicationThemeConfigModel? themeConfig;
  @JsonKey(name: 'configBuilderAdminJsonValues')
  String? configBuilderAdminJsonValues;
  @JsonKey(name: 'configRuntimeAdminJsonValues')
  String? configRuntimeAdminJsonValues;
  @JsonKey(name: 'configBuilderSiteJsonValues')
  String? configBuilderSiteJsonValues;
  @JsonKey(name: 'configRuntimeSiteJsonValues')
  String? configRuntimeSiteJsonValues;
  @JsonKey(name: 'scoreClick')
  int? scoreClick;
  @JsonKey(name: 'scoreSumPercent')
  int? scoreSumPercent;
  @JsonKey(name: 'adminConfigFormFormatter')
  List<GetPropertiesInfoModel>? adminConfigFormFormatter;
  @JsonKey(name: 'userConfigFormFormatter')
  List<GetPropertiesInfoModel>? userConfigFormFormatter;
  @JsonKey(name: 'themeConfigJsonValues')
  String? themeConfigJsonValues;
  @JsonKey(name: 'buildKey1String')
  String? buildKey1String;
  @JsonKey(name: 'buildKey1Value')
  String? buildKey1Value;
  @JsonKey(name: 'buildKey1Files')
  String? buildKey1Files;
  @JsonKey(name: 'buildKey2String')
  String? buildKey2String;
  @JsonKey(name: 'buildKey2Value')
  String? buildKey2Value;
  @JsonKey(name: 'buildKey2Files')
  String? buildKey2Files;
  @JsonKey(name: 'buildKey3String')
  String? buildKey3String;
  @JsonKey(name: 'buildKey3Value')
  String? buildKey3Value;
   @JsonKey(name: 'buildKey3Files')
  String? buildKey3Value;
  @JsonKey(name: 'buildKey4String')
  String? buildKey4String;
  @JsonKey(name: 'buildKey4Value')
  String? buildKey4Value;
  @JsonKey(name: 'buildKey4Files')
  String? buildKey4Files;
  @JsonKey(name: 'buildKey5String')
  String? buildKey5String;
  @JsonKey(name: 'buildKey5Value')
  String? buildKey5Value;
  @JsonKey(name: 'buildKey5Files')
  String? buildKey5Files;
  @JsonKey(name: 'downloadLinkSrcCustomize')
  String? downloadLinkSrcCustomize;
  @JsonKey(name: 'downloadLinkSrc')
  String? downloadLinkSrc;
  @JsonKey(name: 'downloadLinkUpdateSrc')
  String? downloadLinkUpdateSrc;
  @JsonKey(name: 'downloadLinkSrcQRCodeBase64')
  String? downloadLinkSrcQRCodeBase64;
  @JsonKey(name: 'linkFileIdSplashScreenSrc')
  String? linkFileIdSplashScreenSrc;
  // @JsonKey(name: 'downloadLinkSrcByDomainQRCodeBase64')
  // String? downloadLinkSrcByDomainQRCodeBase64;

  // @JsonKey(name: 'filePathOnServer')
  // String? filePathOnServer;

  @JsonKey(name: 'aboutUsTitle')
  String? aboutUsTitle;
  @JsonKey(name: 'aboutUsDescription')
  String? aboutUsDescription;
  @JsonKey(name: 'aboutUsTel')
  String? aboutUsTel;
  @JsonKey(name: 'aboutUsMobile')
  String? aboutUsMobile;
  @JsonKey(name: 'aboutUsFax')
  String? aboutUsFax;
  @JsonKey(name: 'aboutUsEmail')
  String? aboutUsEmail;
  @JsonKey(name: 'aboutUsAddress')
  String? aboutUsAddress;
  @JsonKey(name: 'aboutUsLinkImageId')
  String? aboutUsLinkImageId;
  @JsonKey(name: 'aboutUsLinkImageIdSrc')
  String? aboutUsLinkImageIdSrc;
  @JsonKey(name: 'aboutUsGeolocationlatetitude')
  double? aboutUsGeolocationlatetitude;
  @JsonKey(name: 'aboutUsGeolocationlongitude')
  double? aboutUsGeolocationlongitude;
  @JsonKey(name: 'aboutUsLinkFacebook')
  String? aboutUsLinkFacebook;
  @JsonKey(name: 'aboutUsLinkTwitter')
  String? aboutUsLinkTwitter;
  @JsonKey(name: 'aboutUsLinkGooglePlus')
  String? aboutUsLinkGooglePlus;
  @JsonKey(name: 'aboutUsLinkInstagram')
  String? aboutUsLinkInstagram;
  @JsonKey(name: 'aboutUsLinkWhatsapp')
  String? aboutUsLinkWhatsapp;
  @JsonKey(name: 'aboutUsLinklinkedin')
  String? aboutUsLinklinkedin;
  @JsonKey(name: 'aboutUsLinkYahoo')
  String? aboutUsLinkYahoo;
  @JsonKey(name: 'aboutUsLinkYoutube')
  String? aboutUsLinkYoutube;
  @JsonKey(name: 'aboutUsLinkTelegram')
  String? aboutUsLinkTelegram;
  @JsonKey(name: 'aboutUsLinkPinterest')
  String? aboutUsLinkPinterest;
  @JsonKey(name: 'aboutUsLinkRss')
  String? aboutUsLinkRss;
  @JsonKey(name: 'aboutUsPrivacyPolicyHtmlBody')
  String? aboutUsPrivacyPolicyHtmlBody;
  @JsonKey(name: 'linkFileIdIconSrc')
  String? linkFileIdIconSrc;
  @JsonKey(name: 'linkFileIdLogoSrc')
  String? linkFileIdLogoSrc;
  @JsonKey(name: 'linkMainImageIdSrc')
  String? linkMainImageIdSrc;
  ApplicationAppModel();
  factory ApplicationAppModel.fromJson(Map<String, dynamic> json) =>
      _$ApplicationAppModelFromJson(json);

  Map<String, dynamic> toJson() => _$ApplicationAppModelToJson(this);
}
